# Generated by Django 3.0.6 on 2022-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='username',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('dollar', 'dollar'), ('euro', 'euro'), ('yen', 'yen'), ('pounds', 'pounds')], max_length=250),
        ),
    ]
