# Generated by Django 3.0.6 on 2022-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220321_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Balance',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
