# Generated by Django 3.0.6 on 2022-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220324_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.TextField(blank=True, default=5540013151, null=True),
        ),
    ]
