# Generated by Django 3.0.6 on 2022-03-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220325_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.TextField(blank=True, default='4187 3759 6804 7178', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.TextField(blank=True, default=4752355328, null=True),
        ),
    ]
