# Generated by Django 3.0.6 on 2022-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220325_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card2',
            field=models.TextField(blank=True, default='3132485335499693', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.TextField(blank=True, default=4559916034, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.TextField(blank=True, default='4187334033395486', null=True),
        ),
    ]
