# Generated by Django 3.0.6 on 2022-03-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20220326_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.TextField(blank=True, default=8130599469, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.TextField(blank=True, default='4187118905106577', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card2',
            field=models.TextField(blank=True, default='3132398340826919', null=True),
        ),
    ]
