# Generated by Django 3.0.6 on 2022-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20220330_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.TextField(blank=True, default=1273412873, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.TextField(blank=True, default='4187691070988932', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card2',
            field=models.TextField(blank=True, default='3132590843621350', null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='auc_token',
            field=models.CharField(blank=True, default='000000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.CharField(blank=True, default='otp', max_length=20, null=True),
        ),
    ]
