# Generated by Django 3.0.6 on 2022-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220321_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings'), ('current', 'current')], default='Active', max_length=200),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='Active', max_length=200),
        ),
    ]
