# Generated by Django 3.0.6 on 2022-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usersdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=400)),
                ('mobile_number', models.CharField(blank=True, max_length=400)),
                ('email_address', models.EmailField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings'), ('current', 'current')], default='Savings', max_length=200),
        ),
    ]
