# Generated by Django 3.0.6 on 2022-03-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220323_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='password',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
