# Generated by Django 3.0.6 on 2022-03-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220324_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='verified',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=200),
        ),
    ]
