# Generated by Django 3.0.6 on 2022-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usersdata_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='status',
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='single', max_length=250),
        ),
    ]
